server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoelMaciel/EAD-CONFIG-SERVER-REPO
          default-label: main
          username: JoelMaciel
          password: ${GIT_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
